services:
  vscode-tunnel:
    container_name: code-tunnel
    build:
      context: .
      dockerfile: Dockerfile
    #optional : mount workspace in the host filesystem
    volumes:
     - ./workspace:/home/codeuser/workspace
    
    #optional : add the network
    # networks:
    #   - vscode-network

#optional : add the network 
# networks:
#   vscode-network:
#     external: false
#     name: vscode-network
